### ISSUE TITLE
default oracle properties file minor suggestions

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddnc#10]
I think the username should rather be system than sys. My scripts are made in that light. Of course, later on, if it turns out that we need absolutely to connect as sys, we can leave it like this.

Also, oracle-sid should be rather orcl by default, I think, because probably this will be the most frequent case for the server(s) that we will be using. For example, the current VM prepared by Péter also has the orcl SID.

Of course, I know that you can easily change these, and you only have to do it once for every server, but still I think that generating the dummy default file with the most probable values is the best approach.

**Comment by djavorszky** [comment]
Yup, please make these changes. Thanks!

**Comment by sorin-pop** [comment]
Thank you. Here is the pull request: https://github.com/djavorszky/ddnc/pull/14

**Comment by djavorszky** [comment]
Merged, thank you! :-)
