### ISSUE TITLE
implement CreateDatabase() and a few other methods for Oracle

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddnc#12]
I can start working on this, if we settle for the sqlplus (non OCI) solution.

My idea:
- there would be a "tablespace" or "defaultTablespace" property in the configuration file for Oracle (by default equal to "USERS", then we can set it to e.g LIFERAY_DATA if we know we have created such a tablespace and we want all the new schemas to go there. The current VM we have also has this tablespace)

- it would call sqlplus to run a create_schema.sql (or create_user.sql, or create_database.sql, as you wish) with a content like this:

{code}
create user &1 identified by &2 default tablespace &3 quota unlimited on &3;

grant connect, resource to &1;
{code}

ultimately resulting in something like (after the parameters are replaced) the below being executed:

{code}
create user telefonica_80 identified by test default tablespace LIFERAY_DATA quota unlimited on LIFERAY_DATA;

grant connect, resource to telefonica_80;
{code}

LiferayUp already uses this approach for creating a new schema in an Oracle VM. So I could start by seeing if we can adapt it for ddnc, probably would be a piece of cake. 

Please let me know if I can proceed like this.

**Comment by djavorszky** [comment]
Let's go with the sqlplus approach. For replacing the parameters, check https://golang.org/pkg/text/template/ (and also https://github.com/djavorszky/ddnc/blob/master/io.go#L18-L36), though if you have a better idea, do go with it :-)

**Comment by sorin-pop** [comment]
Pull request: https://github.com/djavorszky/ddnc/pull/15

**Comment by djavorszky** [comment]
Implemented in 91995a3bfa558784c7377bd6ebff1d574eb1316e and 7e7987d8070f877dc48a43c4e0fcb743cc8a60d3
